### ISSUE TITLE
Can't connect - "Error decoding ...AvailableCommands ... Argument type identifier null unknown."

### ISSUE THREAD

**Issue by unilock** [adde0109/Proxy-Compatible-Forge#13]
As mentioned here: https://github.com/adde0109/Proxy-Compatible-Forge/issues/12#issuecomment-1447234919

When attempting to log in, I'm forcibly disconnected, and the following error is printed to the Velocity logs:

```
[17:46:22 INFO]: [connected player] PLAYER_NAME (/192.168.0.1:54918) has connected
[17:46:23 INFO]: [server connection] PLAYER_NAME -> unipack has connected
[17:46:59 INFO]: PLAYER_NAME joined the network
[17:47:00 ERROR]: [server connection] PLAYER_NAME -> unipack: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@598ce0e4
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 1.18.2 State PLAY ID 12
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Argument type identifier null unknown.
    at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:86) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:210) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:88) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity-3.2.0-SNAPSHOT-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
    ... 31 more
[17:47:00 INFO]: [connected player] PLAYER_NAME (/192.168.0.1:54918) has disconnected: Your connection to unipack encountered a problem.
[17:47:00 INFO]: [server connection] PLAYER_NAME -> unipack has disconnected
```

I assume this is because the "command argument wrapper" was removed in [PCF v1.0.0](https://github.com/adde0109/Proxy-Compatible-Forge/releases/tag/1.18.2-1.0.0), which is typically required with modded Fabric backends in the form of [CrossStitch](https://github.com/VelocityPowered/CrossStitch). (specifically in [CommandTreeSerializationMixin.java](https://github.com/VelocityPowered/CrossStitch/blob/master/src/main/java/com/velocitypowered/crossstitch/mixin/command/CommandTreeSerializationMixin.java))

Obviously this was fixed with https://github.com/adde0109/Proxy-Compatible-Forge/commit/10fcddda73733afc785540d6d5a7e5e76a2abf34, but I figured I'd open an issue anyway to at least document the error before a new version of PCF with the fix is released.

Minecraft: 1.18.2, [mod list](https://gist.github.com/unilock/79ac54321a731426092679778234b5c1)
Velocity: `velocity-3.2.0-SNAPSHOT-230.jar` (modern forwarding mode)
Ambassador: v1.2.0-beta
Proxy Compatible Forge: 1.18.2-v1.0.0

(edit: i'm really good at misspelling titles)

**Comment by adde0109** [comment]
This is WIP
