### ISSUE TITLE
unable to connect to server (forge 1.19.2)

### ISSUE THREAD

**Issue by niclan051** [adde0109/Proxy-Compatible-Forge#25]
logs:
```
[12:50:42] [Server thread/INFO] [minecraft/PlayerList]: niclan051[/192.168.1.48:64341] logged in with entity id 3 at (-41.5, 67.0, -87.5)
[12:50:42] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.network.ConnectionData.getChannels()" because "connectionData" is null
        at net.minecraft.commands.Commands.redirect$zzb000$sendCommands$grabPacket(Commands.java:523) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,re:classloading,pl:mixin:APP:pcf.mixins.json:command.CommandsMixin,pl:mixin:A}
        at net.minecraft.commands.Commands.m_82095_(Commands.java:298) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,re:classloading,pl:mixin:APP:pcf.mixins.json:command.CommandsMixin,pl:mixin:A}
        at net.minecraft.server.players.PlayerList.m_11226_(PlayerList.java:590) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.players.PlayerList.m_11289_(PlayerList.java:483) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:176) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pcf.mixins.json:login.ServerLoginPacketListenerPlaceholderMixin,pl:mixin:APP:pcf.mixins.json:login.ModernForwardingMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pcf.mixins.json:login.ServerLoginPacketListenerPlaceholderMixin,pl:mixin:APP:pcf.mixins.json:login.ModernForwardingMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pcf.mixins.json:login.ServerLoginPacketListenerPlaceholderMixin,pl:mixin:APP:pcf.mixins.json:login.ModernForwardingMixin,pl:mixin:A}
        at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,re:classloading,pl:mixin:APP:pcf.mixins.json:login.ConnectionMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:1623) [?:?] {}
[12:50:42] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: niclan051 lost connection: Invalid player data
[12:50:42] [Server thread/INFO] [minecraft/MinecraftServer]: niclan051 left the game
[12:50:42] [Server thread/WARN] [minecraft/Connection]: handleDisconnection() called twice
```
also if i dont have the mod on the server and try to connect through the proxy, i get this error:
![image](https://github.com/adde0109/Proxy-Compatible-Forge/assets/96299784/a1be41f4-1ed9-4680-9a02-a7dfbabcdbf4)

**Comment by niclan051** [comment]
nevermind joining with a forge client fixed the issue

**Comment by niclan051** [comment]
nevermind joining with a forge client fixed the issue
