### ISSUE TITLE
Player kicked, but client does not detect that.

### ISSUE THREAD

**Issue by Kaloyan501** [adde0109/Proxy-Compatible-Forge#35]
OS: Arch Linux 64-bit, latest kernel
Forge Version: 47.3.7
Proxy-Compatible-Forge version: Latest

Forge server says com.mojang.authlib.GameProfile@13d3f26[id=!UUID!,name=!My Username!,properties={},legacy=false] (!IP!) lost connection: Disconnected

Stuff in !! is not what it's actually printing, I'm just redacting IP's and stuff.

**Comment by p0t4t0sandwich** [comment]
Are you using Ambassador on your Velocity proxy?
What are the full logs on the Forge server/proxy/Forge client? (Use MCLogs to share the logs, as they redact IPs and other sensitive info. Player names/UUIDs are public knowledge and don't really need to be redacted)

**Comment by CREW8** [comment]
Hello together,

I have the same error with my AllTheMods10 Server. I get the same Error Message on my ATm10 NeoForge Server as @Kaloyan501 states in his message above. 

> Forge server says com.mojang.authlib.GameProfile@13d3f26[id=!UUID!,name=!My Username!,properties={},legacy=false] (!IP!) lost connection: Disconnected

Additionally i get this error log in my Velocity Console:

```
[22:59:03 ERROR]: [server connection] PlayerXYZ -> atm10: exception encountered in com.velocitypowered.proxy.connection.backend.ConfigSessionHandler@7a3cb38
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.config.KnownPacksPacket Direction CLIENTBOUND Protocol 1.21 State CONFIG ID e
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.velocitypowered.proxy.util.except.QuietDecoderException: too many known packs
[22:59:03 INFO]: [server connection] PlayerXYZ -> atm10 has disconnected
[22:59:03 ERROR]: [connected player] PlayerXYZ (/88.888.888.88:88888): unable to connect to server atm10
java.io.IOException: Unexpectedly disconnected from remote server
	at com.velocitypowered.proxy.connection.backend.ConfigSessionHandler.disconnected(ConfigSessionHandler.java:335) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:126) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueOutboundHandler.channelInactive(PlayPacketQueueOutboundHandler.java:79) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at com.velocitypowered.proxy.protocol.netty.PlayPacketQueueInboundHandler.channelInactive(PlayPacketQueueInboundHandler.java:75) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:280) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:412) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:377) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1352) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:850) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:811) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[22:59:03 INFO]: [connected player] PlayerXYZ (/88.888.888.88:88888) has disconnected: Unable to connect you to atm10. Please try again later.
```

**Comment by p0t4t0sandwich** [comment]
Add the `-Dvelocity.max-known-packs=264` startup arg, replacing the number with roughly the `number-of-mods`x`1.5` to make sure the number is bumped high enough

**Comment by CREW8** [comment]
Thank you for the fast reply! This worked and solved the issue!

**Comment by Kaloyan501** [comment]
@p0t4t0sandwich Hello, sorry for bumping this issue and not replying. I am using ambassador on my forge client, I will try the fix you have to @CREW8 and see if it fixes things.

**Comment by Kaloyan501** [comment]
I was using the latest version of Ambassador on my Velocity proxy at the time, will try this fix and if it doesn't work, I will provide the full logs from the proxy, forge client and server.

**Comment by Kaloyan501** [comment]
Here are the Velocity proxy log: https://mclo.gs/K2Iy1W0
Here are the Paper server logs: https://mclo.gs/NQQbSaw (Connection to it is successful)
Here are the Forge server logs: https://mclo.gs/JZBNBj5
What I have checked: 
- Latest version of Ambassador is installed on the Velocity proxy. 
- Latest version of PCF is installed on the forge server. 
- Forwarding secret matches one from Velocity proxy. 
- Online-mode on the Forge server is set to false
- Here is my PCF-common with the key redacted
#Modern Forwarding Settings
[modernForwarding]
	forwardingSecret = "<redacted>"

[commandWrapping]
	#List of argument types that are not vanilla but are integrated into the server (found in the Vanilla registry)
	moddedArgumentTypes = ["livingthings:sampler_types"]
- Port on Velocity Proxy matches actual server port

**Comment by Kaloyan501** [comment]
I don't know if this is relevant info, but all my servers are managed under Crafty Controller, which connect to the server port to get stuff like is the server online, its motd, etc.

**Comment by Kaloyan501** [comment]
I also have 2 questions. First, does it matter in what order I starts the proxy and 2 servers, second is it a problem to place a larger value to -Dvelocity.max-known-packs because I multiplied the amount of mods by 1.8, not 1.5

**Comment by Kaloyan501** [comment]
Do I need to count the mods that are shown in places like the CurseForge client or the amount that is listed on the mods screen in minecraft?

**Comment by Kaloyan501** [comment]
Also, I am using Forge version 47.3.7, will try to update later and post if anything different happens.

**Comment by Kaloyan501** [comment]
I updated ambassador, velocity and PCF before trying the fix.

**Comment by Kaloyan501** [comment]
New development of the bug: At first, when I typed /server survival1, I just got Connection Reset, now minecraft says Please Reconnect. The server still says that it received and empty payload on channel fml:handshake every time.

**Comment by p0t4t0sandwich** [comment]
"Please Reconnect" is normal, that's how Ambassador resets the Forge handshake+resources when switching servers.

**Comment by Kaloyan501** [comment]
@p0t4t0sandwich Yeah, I know, it was just wasn't displaying it, and I just wrote it here if it's related to the issue. I am still receiving the fml:handshake error on the forge server side. Should I make a new issue for this?

**Comment by p0t4t0sandwich** [comment]
Is that after reconnecting to the proxy after the `Please Reconnect` message? If so, try connecting to the server directly, instead of switching servers.
Valkyrien Skies operates really poorly in proxied setups. With the lack of a real error I'd guess that would be the main culprit, hard to tell without additional info regarding the modpack.

**Comment by Kaloyan501** [comment]
I get the fml:handshake error when I type /servers to connect to my Forge server and after I try to reconnect to the proxy like the Please reconnect message told me.

**Comment by p0t4t0sandwich** [comment]
No, I mean make the Forge server the primary server and see if that works

**Comment by Kaloyan501** [comment]
>  With the lack of a real error I'd guess that would be the main culprit, hard to tell without additional info regarding the modpack. Here is the modpack I am using: https://www.curseforge.com/minecraft/modpacks/workload/files/6046700

**Comment by Kaloyan501** [comment]
I also noticed I had a mod called Simple Login on the server, will try to remove that, see if it works, and if it doesn't, try to change the forge server to primary.

**Comment by Kaloyan501** [comment]
Ok, so I haven't removed Simple Login yet, but I noticed when I try to reconnect to the Forge server trough the proxy after the disconnect message, my client gets stuck on Encrypting... for a solid 30 seconds and then just says Disconnected. When It is on encrypting, nothing shows up on the Forge server console, when the client says Disconected, nothing shows up on the console again (no FML error) but the proxy says  [connected player] MineManiack (<REDACTED>): read timed out

**Comment by Kaloyan501** [comment]
Simple Login is not the problem, I also get stuck on Encrypting when I change the Forge server to the main one in the proxy. No message is displayed on the Forge server, but the proxy says [14:01:01 ERROR]: [connected player] MineManiack (/192.168.0.101:58578): read timed out. There is some communication between the proxy and the server, because when I set it as the secondary and try to connect from my Paper server, it throws the FML error and shows the disconnected message.

**Comment by Kaloyan501** [comment]
When I connect to the server directly, everything works just fine.

**Comment by p0t4t0sandwich** [comment]
Sorry, missed these issue comments in my notifications.
Please share the full, unedited logs, from your Client, Velocity Proxy, and Forge server (<https://mclo.gs/>)
And when you encounter errors in Github issues, please share the full log, along with the error message, otherwise it's nearly impossible to help.

**Comment by Kaloyan501** [comment]
> Here are the Velocity proxy log: https://mclo.gs/K2Iy1W0 Here are the Paper server logs: https://mclo.gs/NQQbSaw (Connection to it is successful) Here are the Forge server logs: https://mclo.gs/JZBNBj5 What I have checked:
> 
> * Latest version of Ambassador is installed on the Velocity proxy.
> * Latest version of PCF is installed on the forge server.
> * Forwarding secret matches one from Velocity proxy.
> * Online-mode on the Forge server is set to false
> * Here is my PCF-common with the key redacted
>   #Modern Forwarding Settings
>   [modernForwarding]
>   forwardingSecret = ""
> 
> [commandWrapping] #List of argument types that are not vanilla but are integrated into the server (found in the Vanilla registry) moddedArgumentTypes = ["livingthings:sampler_types"]
> 
> * Port on Velocity Proxy matches actual server port

I already did that.
I don't have the client logs, will retest everything with new versions of Forge, Paper, Velocity, Ambassador and PCF is any new versions are available, hopefully later today when I have time.

**Comment by Kaloyan501** [comment]
> > Here are the Velocity proxy log: https://mclo.gs/K2Iy1W0 Here are the Paper server logs: https://mclo.gs/NQQbSaw (Connection to it is successful) Here are the Forge server logs: https://mclo.gs/JZBNBj5 What I have checked:
> > 
> > * Latest version of Ambassador is installed on the Velocity proxy.
> > * Latest version of PCF is installed on the forge server.
> > * Forwarding secret matches one from Velocity proxy.
> > * Online-mode on the Forge server is set to false
> > * Here is my PCF-common with the key redacted
> >   #Modern Forwarding Settings
> >   [modernForwarding]
> >   forwardingSecret = ""
> > 
> > [commandWrapping] #List of argument types that are not vanilla but are integrated into the server (found in the Vanilla registry) moddedArgumentTypes = ["livingthings:sampler_types"]
> > 
> > * Port on Velocity Proxy matches actual server port
> 
> I already did that. I don't have the client logs, will retest everything with new versions of Forge, Paper, Velocity, Ambassador and PCF is any new versions are available and send all the logs, hopefully later today when I have time.

**Comment by Kaloyan501** [comment]
> > > Here are the Velocity proxy log: https://mclo.gs/K2Iy1W0 Here are the Paper server logs: https://mclo.gs/NQQbSaw (Connection to it is successful) Here are the Forge server logs: https://mclo.gs/JZBNBj5 What I have checked:
> > > 
> > > * Latest version of Ambassador is installed on the Velocity proxy.
> > > * Latest version of PCF is installed on the forge server.
> > > * Forwarding secret matches one from Velocity proxy.
> > > * Online-mode on the Forge server is set to false
> > > * Here is my PCF-common with the key redacted
> > >   #Modern Forwarding Settings
> > >   [modernForwarding]
> > >   forwardingSecret = ""
> > > 
> > > [commandWrapping] #List of argument types that are not vanilla but are integrated into the server (found in the Vanilla registry) moddedArgumentTypes = ["livingthings:sampler_types"]
> > > 
> > > * Port on Velocity Proxy matches actual server port
> > 
> > 
> > 

I already did that. I don't have the client logs, will retest everything with new versions of Forge, Paper, Velocity, Ambassador and PCF is any new versions are available and send all the logs, hopefully later today when I have time.

**Comment by p0t4t0sandwich** [comment]
I more mean, share the logs from your tests, as it'll have updated info from that attempt

**Comment by p0t4t0sandwich** [comment]
`valkyrienskies` is also a known "probably incompatible" mod when it comes to switching servers, in which case you'd make the Forge server the primary and see if that connects fine. If it does, then you'd use Velocity's forced-hosts feature to proxy the server on a different subdomain.

**Comment by Kaloyan501** [comment]
Logs when valkyrienskies is ENABLED, auth1 (Paper server) is default.
https://mclo.gs/8ifN9GB - Client Logs
https://mclo.gs/ZwOhP67 - Proxy Logs
https://mclo.gs/eMAO8md - Paper Server Logs
https://mclo.gs/WNtRTjf - Forge Server Logs

Logs when valkyrienskies is ENABLED, survival1 (Forge server) is default.
https://mclo.gs/3XcQO2Q - Client Logs
https://mclo.gs/fA4Gt43 - Proxy Logs
https://mclo.gs/pp6Aldp - Paper Server Logs
https://mclo.gs/kM8OAy8 - Forge Server Logs

Logs when valkyrienskies is DISABLED, survival1 (Forge server) is default.
https://mclo.gs/0meA08l - Client Logs
https://mclo.gs/F26f3aK - Proxy Logs
https://mclo.gs/WUjrFoR - Paper Server Logs
https://mclo.gs/Dg8c1QQ - Forge Server Logs

The servers shutting down is me doing that manually to get the full logs into latest.log, not them crashing.
All test end up stuck at the Encrypting screen on the client side, after trying to connect to the Forge server.

**Comment by Kaloyan501** [comment]
@p0t4t0sandwich Any updates on this issue?

**Comment by p0t4t0sandwich** [comment]
Haven't had that much time to work on things lately, just took a look and it doesn't look like there's much too much to go off of. I'm doubtful but `moonlight` might be a lead. Could just be down to trial and error/binary search to find the incompatible mod(s).

**Comment by p0t4t0sandwich** [comment]
Would be worth a test after the next PCF update, where I'm hoping to fix that FFAPI incompatibility

**Comment by Kaloyan501** [comment]
I have switched to NeoForge, but I may test things if I have time.
